#!/usr/bin/env bash
# add a redirect page
apt-get -y update
apt-get -y install nginx
utf allow 'Nginx HTTP'

echo "Holberton School" > /var/www/html/index.html
sed -i "/server_name _;/a\n\nrewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" "/etc/nignx/sites-available/default"
service nginx start
