#!/usr/bin/env bash
# The story of /etc/passwd
IFS=:
while read -r user p uid gid comm home int ; do
    echo "The user $user is part of the $gid gang, lives in $home and rides $int. $uid's place is protected by the passcode $p, more info about the user here: $comm"
done < /etc/passwd
