#!/usr/bin/env bash
# print "Holberton School" 10 times to stdout
# after the 9th iteration "Hi" should be printed
i=0
while [ $i -lt 10 ] ; do
      i=$((i+1))
      echo "Holberton School"
      if [ $i -eq "9" ]
      then
	echo "Hi"
      fi
done
